name: 'actions'

on: ['push', 'pull_request']
jobs:
  source-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install --global yarn
      - run: |
          yarn install
          yarn run build --prod --output-path ../server/public
        working-directory: 'ui'
      - run: |
          yarn install
          yarn run build
        working-directory: 'server'